### ISSUE TITLE
Guvenlik Bilgisayarı Sorunu

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#1]
Diskte müdahele edilemiyen dosyalar var
Formatlanıp, mevcut şirket lisanslarından biri kurulması gerekiyor.
Üzerindeki kamera izleme programının ayarları ile birlikte yeni bilgisayara gösterilmesi gerekiyor.

**Comment by 1OrhanCan** [comment]
bilgisayar alınıp formatlanıp kamera uygulaması kuruldu fakat kamera uygulamasını çalıştıramadığı için farklı bilgisayar kuruldu
