### ISSUE TITLE
İp telefon kurulumu

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#101]
Üretim metal alanına ip telefon kurulacak.kurulum yeri Ali bey ile görüşülecek.

 

- [x] Kurulum öncesi data kablosu en yakın switchten çekilecek.
- [x]  Telefon ismi Metal ve dahilisi 2003 olacak.
- [x]  Telefon rehberine dahili eklenecek.
-0555 013 30 54 Ali abi metale yönlenecek

**Comment by 1serkanduran** [comment]
Telefon kuruldu. Ayarları yapıldı. Kullanıma hazır hale getirildi.
