### ISSUE TITLE
Showroom ürünlerin üzerine isimlikler konulması

### ISSUE THREAD

**Issue by 1serkanduran** [semihpro/RoderTeknikservis#102]
Showroom ürünlerin üzerine plexi formatı şeklinde logo ve ürün adının olduğu tasarım yapılacak
-Handan hanımla ürünlerin isimleri alınacak
-Çıktılar alınıp yerleştirilecek.

**Comment by 1OrhanCan** [comment]
Handan hanım ile showroomdan isimler alındı

**Comment by semihpro** [comment]
Handan hanım bekleniliyor.

**Comment by 1OrhanCan** [comment]
İsimlikler showrooma bırakıldı handan hanım yerleştirmesini yapacak
