### ISSUE TITLE
Acil kırtasiye listesinin alınması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#11]
Can beye (05331351276) acil alınacak listesi gönderildi. Malzeme listesi aşağıdadır.

- [x] vga to hdmi converter
- [x] kablo test cihazı ethernet kabloları için
- [x] Kalem pil, ince kalem pil
- [x] Flash bellek 64gb 5 adet
- [x] Tornovida seti Hassas çok uçlu (Laptop bakımlarında kullanılacak)
- [x] Router 10-20 kullanıcıda tıkanmıyacak, sorun yaşatmıyacak seviyede bir cihaz (orta seviye)

**Comment by 1serkanduran** [comment]
Semih Bey teslim aldı.
