### ISSUE TITLE
Planlama bilgisayarının taşınması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#12]
Planlama odasından bilgisayar ve yazıcıların taşınarak kurulumunun Teknik ofise yapılması

**Comment by 1serkanduran** [comment]
-Planlama ofisindeki Ensar Bey'in bilgisayar, barkod yazıcıları, telefonu teknik ofise taşındı.
-Ensar Bey'in bilgisayarı, barkod yazıcı, telefonu teknik ofise kuruldu.
-Ensar Bey'in bilgisayarı yazıcıya bağlandı.
-Kablo düzenlemeleri yapıldı.
-Yasin Bey'in mail bilgileri yeni bilgisayara kuruldu ve ayarları yapıldı.
-Yasin Bey'in telefonu taşındı.
-Enes Bey'in mail adresi yeni bilgisayarına taşındı ve ayarları yapıldı.
