### ISSUE TITLE
Yedek işlemlerinin kontrollü bir şekilde gece başlatılması ve takip edilmesi

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#135]
12-01-2023 tarihi için yedeklerin gece yapılması ve yedek takibinin yapılması.

**Comment by 1serkanduran** [comment]
Yedek işlemi hafta sonu başlatıldı. Muhasebe ve ortak klasörü verdi. Bugün bu klasörler tekrar başlatıldı. Gece takibi yapılacak.

**Comment by 1serkanduran** [comment]
Ortak klasörü tekrar hata verdi. Tekrar başlatıldı.

**Comment by semihpro** [comment]
yedek işlemleri alındı fakat sistemli yedek çalışmasında sıkıntılar var. Farklı bir sistem ile deneyeceğiz. O zamana kadar manuel yedek almaya devam edeceğiz.
