### ISSUE TITLE
Kapasite raporunun hazırlanması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#137]
Kapasite raporu örneği bulundu ve 

- [x] Firma Mülkiyet Makine ve Techizat Listesi
- [x] Yıllık Üretim Kapasitesi
- [x] Yıllık Tüketim Kapasitesi
- [x] Yetkili İmza Sürküsü

alanlarının doldurulması gerekiyor.

- [x] Satsu ile görüşülüp evrak teyidinin yapılması.

Yukarıdaki işlemler sonucu gerekli kalan adımlar yapılarak, Kapasite raporunun alınması.

**Comment by 1OrhanCan** [comment]
Firma Makina Ve Teçhizat listesi çıkartıldı

**Comment by 1OrhanCan** [comment]
Yıllık tüketim kapasitesi çıkartıldı

**Comment by 1OrhanCan** [comment]
Kapasite raporunun son hali Fatma hanıma gönderildi eksik veya değişen alanların güncellenmesi için

**Comment by semihpro** [comment]
Gerekli bilgiler Mali müşavir Hamit beye imzalaması için iletildi. İmza ve mühürlemesi için mail adresine gönderildi. Sonrasında kargo ile bize göndermesi istedik, bekliyoruz.

**Comment by semihpro** [comment]
Kargo geldi, evraklar tamamlandı, 6000 tl çalışan için 2200 tl TOBB için ödeme yapıldıktan sonra belge satsoya iletilecek.

**Comment by 1OrhanCan** [comment]
Kapasite Raporu çıktı
