### ISSUE TITLE
Handan mail kontrol

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#140]
- [ ] H.pirildar mailin Handan hanımın asıl maili. handanpirildar veya handa.pirildar mailleri direk ana maile yönlenmesi gerekiyor.
- [ ] Satis1, 2,3,...9 a kadar olan satis mailleri de handan hanıma yönlenilecek.
- [ ] Yukarıdaki mailler yok ise açılacak ve yönlenme işlemi yapılacak.

**Comment by 1OrhanCan** [comment]
h.pirildar@nexoff.com şuanda aktif olan kullanılan mail diğer mailler buraya yönlendirilecktir

**Comment by 1OrhanCan** [comment]
yönlendirme yapıldı handan hanıma mesaj ile cevap verildi
