### ISSUE TITLE
HİZMET YETERLİLİK BELGESİ

### ISSUE THREAD

**Issue by 1OrhanCan** [semihpro/RoderTeknikservis#155]
TSE ile görüşüldü bitme tarihinde TSE tarafından firma aranıp fabrikaya görüşmeye geliyorlarmış

**Comment by semihpro** [comment]
TSE işlemlerini bitirdikten sonra belgeyi alacağız. Belge son tarihi 20.12.2023

**Comment by semihpro** [comment]
Bizim patentlere İbrahim Aydın (Sakarya Patent) ilgileniyor.
Telefon numarası 0532 645 36 75

**Comment by 1OrhanCan** [comment]
hastanın hyb belgesi
Makro muayneden ölçüm aletinin kalibrasyon sertifikası ve topraklama yetki belgesi 
makrodan kompresör fenni muayne
periyodik kontrol anlamında

**Comment by semihpro** [comment]
gerekli belgeler alındı ve ibrahim beye iletildi.

**Comment by semihpro** [comment]
İbrahim Aydın (Sakarya Patent) ın bizim ile bir bağlantısının olmadığı, kesilen fatura sonucu ve Samiran hanımın takibi sonucu ortaya çıkmıştır. Kuruma ödeme bu yüzden yapılmamıştır.
