### ISSUE TITLE
Katalog bilgilerinin Tuyap sayfasına girişleri

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#156]
- Geçen senenin katalog ürünlerinin aşağıdaki linkteki adrese aktarılması
- Güncel katalog ürünlerinin aşağıdaki linkteki adrese aktarılması
http://forms.tuyap.com.tr/mytuyap/s/KatilimciFormlari/Urunler.php
not: (ürün ekleme işlemleri sırasında Hakan Güçbilmez'e danışabilirsiniz.)

![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/3d9caf21-dacd-4524-8c87-a74b2576ec10)

**Comment by 1serkanduran** [comment]
10 tane ürün Semiran hanım ile birlikte beğenilerek eklendi.
