### ISSUE TITLE
Nexoff site üzerinde fiyat ve güncellemeler yapılması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#159]
-Ürünler güncellenecek
-Fiyatlar kaldırılıacak

**Comment by semihpro** [comment]
Yabancı dil kısmında eksik olan ürünler tamamlanacak. 
Fiyatlar kısmı sağ kısımda gelmişti.
Katalog mevcut olan silinmeden eski katalog menüye 2021 katalog isminde eklenilecek.
Seo çalışması yapılacak. Chatgpt gibi araçlar ile siteye belirili aralıklarla veri girişi yapılacak. Blog yazısı olabilir. Ürün eklenilip çıkarılabilir.

**Comment by 1OrhanCan** [comment]
fiyatlar kaldırıldı
