### ISSUE TITLE
Fuar öncesi proje hosting işlemleri

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#161]
- [ ] projemiz Satış projesini yüklemek için hosting ve domain asp.net alınacak.
- [ ] projemiz müşteri bilgilerini almak için için domain ve hosting alınacak. (Platform belli değil)

**Comment by 1serkanduran** [comment]
güzel hostinge subdomain hakkında bilgi soruldu.

**Comment by semihpro** [comment]
Hosting hizmeti alındı 480 TL Yıllık 12/01/2024
