### ISSUE TITLE
Fuar davetiyesi için tasarım yapılması istendi.

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#162]
Proje bölümünden aşağıdaki tasarıma benzer tasarım yaptırılacak. Semirhan hanıma bilgisi verilecek. 
Bu resim müşterilere davet için kullanılacak.
![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/8626dde0-c050-48d4-8d78-4c256216f1e5)

**Comment by 1OrhanCan** [comment]
Tüyap ile iletişime geçildi sitedeki mevcut davetiyede hata vardı dönüş yapacakları konu ile ilgili

**Comment by 1OrhanCan** [comment]
Tüyapın sitesinde şablon hatalı geliyordu düzeltildi Görsel tasarım yapılcak

**Comment by semihpro** [comment]
Davetiyeler oluşturuldu. Yüklediğim linki aşağıdadır.
https://drive.google.com/drive/folders/1Dxs648eWY4Ldwrnj45EBsk_Ru4f_DUGW?usp=sharing

![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/f0d81961-17a0-449f-abba-47cc1aeb0c77)
