### ISSUE TITLE
Whatsapptan gelen mesajdaki video işlerinin yapılması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#169]
Sayın Üyemiz,
OMSİAD Yönetim Kurulu “Ofis Mobilya Sektörü, OMSİAD ve Üye Firmalarının hedef ülkelerdeki potansiyel ofis mobilya alıcılarına ve fuar ziyaretçilerine ulaşılarak  bilinilirliğini artırmak ve ihracatımızı büyütmek” amacı ile küresel iletişim araçlarını  kullanılarak tanıtım ve reklam çalışması yapılmasına karar vermiştir.
Bu sebeple 20 Aralık 2023 Çarşamba mesai bitimine kadar info@omsiad.org.tr adresine; 
1.3 adet minimum 1800x1800 px güncel ürün görselinizi,
2.dijital ortamda ürün kataloglarınızı,
3.firma tanıtım videonuzu,
4.reklam videolarınızı,
5.vektörel logonuzu,
6.firmanızın en çok ihracat yaptığı 3 ülke ismini,
7.2024 yılı hedef olarak belirlediğiniz 3 ülke ismini
göndermenizi önemle rica ederim.
Saygılarımla,

**Comment by 1OrhanCan** [comment]
Videolar tamamlandı

**Comment by semihpro** [comment]
Diğer bilgiler eklendi ve info@omsiad.org.tr adresine link şeklinde gönderildi.
https://drive.google.com/drive/folders/1GcHVWyrKZMVTmoQ8mUm1c6t07ozWjvqI?usp=sharing
