### ISSUE TITLE
Rapor tasarımın dik şekilde tekrardan tasarlanması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#170]
Semirhan hanımın isteği üzerine mevcut tasarım dikey ve rapor da resimler kare olacak şekilde bir rapor tasarımı yapılacak.

**Comment by semihpro** [comment]
Orhan düzenliyor.

**Comment by 1OrhanCan** [comment]
Bütün Rapor tasarımları dik şekilde tasarlandı siteye yüklendi raporun sağ tarafı kaymış olarak geliyor
