### ISSUE TITLE
Katalog yeni sayfa krokisi

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#171]
![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/002b2820-aaf8-4a55-85b4-bdd7f9121530)

![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/42f32748-7d16-4ba4-ae74-4012fe6ef001)
![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/32dcabc4-0d0f-48a2-a055-420c5518fb61)
![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/9dd78d49-0535-4750-b822-1132328eda4a)
![image](https://github.com/semihpro/RoderTeknikservis/assets/10020140/46b4e3bf-d6cf-407e-ba2f-d09a3d2c03e4)

**Comment by 1serkanduran** [comment]
Katalog prototip oluşturuldu son geliştirmeleri ezgi hanımla birlikte revizyon yapılıyor. Yarın sabah bakılacak.
