### ISSUE TITLE
Fuar sunum hazırlanması

### ISSUE THREAD

**Issue by 1serkanduran** [semihpro/RoderTeknikservis#18]
Ocak ayı fuarda kullanılmak üzere ürün görsellerinin tanıtıldığı sunum hazırlaması

**Comment by 1serkanduran** [comment]
-Daha önce yapılan çalışmalar incelendi ve dosyalara bakıldı.
-Sunum hazırlandı. 
-Test için televizyon bekleniyor.

Sunumda daha önce yapılan çalışmaların renderlerı olacak. Tanıtım videosu, çalışmalar sunumu ve katalog bir arada olacak şekilde ayarlanılıyor.

**Comment by 1serkanduran** [comment]
Son düzenlemeler tamamlandı. Test için tv bekleniyor. Sunumlar 
205/2024 fuar/son klasörünün içinde

**Comment by semihpro** [comment]
Bu issueyi kapıyorum. Fuar bitti.
