### ISSUE TITLE
WEB SİTESİ EKSİKLER

### ISSUE THREAD

**Issue by 1OrhanCan** [semihpro/RoderTeknikservis#198]
- [x] Satış ekranında sağ alttaki toplamlar güncellenmeli
- [x] Satış yaparken ürün ekleme kısmından her ürün tek tek ekleniyor tek seferde birden fazla ürün eklenmeli
- [x] Login sayfasında kayıt oluşturma yapılcak 
- [x] Döviz kurları getirilcek
- [x] Satış ekranında döviz seçimi olmalı

**Comment by semihpro** [comment]
Kayıt oluşturma işlemi iptal edildi ve kullanıcılar tablosu editleme ve listeleme projeye eklendi.
