### ISSUE TITLE
MUHASEBE - İP TELEFON DEĞİŞİKLİĞİ

### ISSUE THREAD

**Issue by 1OrhanCan** [semihpro/RoderTeknikservis#203]
Fatma hanımın telefonunda bağlantı problemi var farklı bir telefonla değiştirilcek

**Comment by 1serkanduran** [comment]
Kontrol edildi. Hatanın anlık olduğu tespit edildi. Büyük bir problem olduğunda tekrar bakılacak.
@1OrhanCan
