### ISSUE TITLE
Fuar alanı İSG belgesi yollanması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#209]
Semiran hanımın isteği üzerine fuar alanına gidecek kişilerin belgelerinin tedariği ve kişilerin tespiti:

**Comment by 1serkanduran** [comment]
Fatma hanım belgeleri hazırlıyor ve  gönderecek.

**Comment by semihpro** [comment]
Fatma hanım aşağıda verdiğim kişilerin ISG belgelerini yolladı.
Samiran K.
Handan P.
Osman T.
Semih Ç.
Orhan Can B.
Gülizar Y.
Hakan G.
Aytaç A.
Osman P.
Savaş K.
Ferudun K.

**Comment by semihpro** [comment]
Çağatay A. için Cevap bekleniyor
Rohat S. kiişisi bilgisi ne yapılacak bilmiyorum.

**Comment by semihpro** [comment]
İşlemler yapıldı gerekli İSG belgeleri Fatma hanım tarafından giderilerek, IFM sitesine yüklendi.
