### ISSUE TITLE
Sigorta sicil belgesi yerinden alınması

### ISSUE THREAD

**Issue by 1serkanduran** [semihpro/RoderTeknikservis#217]
Sanayi bilim odasına gidildi. Bilgi alındı.
-Şirket vizesinin bitmiş olduğu söylendi.
-Yenilenmesi için sanayi sicil belge sistemine girip firma yanındaki ok butonuna basıp gerekli adımları ilerlemek ve gerekli evrakların yüklenmesi gerekiyor.(Kapasite raporu)
-Başvuru yapıldıktan sonra otomatik oluşacakmış.
@1OrhanCan

**Comment by semihpro** [comment]
Konu Ensara whatsup üzerinden iletilti.
