### ISSUE TITLE
Güncel fuar işleri

### ISSUE THREAD

**Issue by 1serkanduran** [semihpro/RoderTeknikservis#218]
- [ ] Panel kapora işlemleri
- [x] Kataloglar toplanacak sevk ekibine verilecek
- [x] Qr çıkartılacak
- [x] Freyja ve diğer masalar için hikaye yazılacak
- [x] Tv sunum kontrol edilecek
- [ ] Pos cihazı kontrol edilecek
- [x] Yazıcı ayarlanacak
- [ ] Raporlara termin kur iban gibi bilgiler yazılacak örnek metine bakılacak
Pazartesiye kadar tüm işler bitmiş olacak

**Comment by 1serkanduran** [comment]
tv sunum için referanslar eklendi tekrar test edilecek.

**Comment by 1OrhanCan** [comment]
Fiyat Listesi Pdfi Dolara çevrildi

**Comment by 1serkanduran** [comment]
qr ve masa takımları hikayeleri tamamlandı. Baskıya gidecek

**Comment by 1OrhanCan** [comment]
Baskıya gidildi QR kod , Fiyat listeleri ve Masa isimlikleri Sipariş verildi cuma öğleden sonra 1 de teslim alıncak

**Comment by semihpro** [comment]
Bu issue yapıldı.
