### ISSUE TITLE
UPS klima arızası tespiti

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#220]
Rutün kontroller sonrası 16.01.2024 tarihinde çalışmadığı tespit edildi. Gerekli bilgilendirme Esra hanıma bugün iletildi. Esra hanım klimacıları aradı. Arıza tespiti takip edilecek.

**Comment by 1OrhanCan** [comment]
Klimanın şarteli kapalı olduğu için çalışmıyordu
