### ISSUE TITLE
Ensar Aydemir bilgisayarının planlama departmanına taşınması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#232]
Ofise gerekli masa sarf malzemeleri taşındıktan sonra bilgisayar ve gerekli diğer sarf malzemeleri taşınacak.

**Comment by cansezer54** [comment]
Tüm bilgisayar ve bileşenleri taşındı extra swich ve ek priz kondu.Test edildi sorunsuz çalışıyor.
