### ISSUE TITLE
İnsan kaynakları için Yazıcı kurulumu

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#259]
İnsan kaynakları personeli Tuğba hanıma hp yazıcı kurulumu yapılacak.

**Comment by cansezer54** [comment]
gerekli yazıcı sürücüsü indirilerek gerekli kurulum yapıldı.test edildi sorunsuz çalışılmakta tek dikkat edilmesi gereken konu toner kartuşunun takıldığı kapak tam kapanmıyor hataya sebebiyet veriyor. bantla yapıştırılarak sorunun önüne geçildi.
