### ISSUE TITLE
Teknikofis yeni bilgisayar ve ağ yapısı

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#29]
- [x] Ethernet kablosu çekilmesi
- [x] Elektrik kablosu çekilmesi
- [x] Ip telefon ayarlarının yapılması
- [x] Ip telefon isminin diğer telefonlara isminin rehberlerine tanımlanması
- [x] Email Adreslerinin açılması

**Comment by 1OrhanCan** [comment]
ethernet kabloları çekildi, Elektrik kablosu çekildi, Kablo kanalından geçirildi, ip telefon ayarları yapıldı, Mail adresleri açıldı

**Comment by 1OrhanCan** [comment]
ip telefonların hepsinin arayüzüne girilip yeni eklenen telefonlar rehberlere eklendi
