### ISSUE TITLE
Yedekleme işlemi

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#3]
- [x] Günlük dosya paylaşım klasörleri yedek ayarları yapıldı. 

- [x] Sql yedek işlemi ise manuel olarak şuan yaptım. Bilgiislem klasörüne attım. 

- [ ] Ama bununla ilgili sql management tan bir job tanımı yapılabilir yada ayrı bir sql backup uygulaması ile düzenli olarak yedek işlemi gerçekleştirilmeli

**Comment by 1serkanduran** [comment]
13.01.2024 tarihli yedek alma işlemi ortak klasörü hariç sorunsuz tamamlandı.

**Comment by semihpro** [comment]
Bu issueyi burada kapıyorum.
