### ISSUE TITLE
Teknik Ofis için bilgisayar isteği

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#43]
Osman beyin isteği, 

- [x] Teknik ofis için 1 adet masaüstü bilgisayar
- [x] Ofis uygulamaları
- [x] Diğer Programlar
- [x] Outlok ayarları
- [x] Yazıcılar

kurularak teslim edilecek.

**Comment by semihpro** [comment]
Osman beyin ofisindeki masaüstü bilgisayarı Teknik ofise taşınacak ve kurulumlar buna yapılacak. Kendisinin isteği.

**Comment by 1serkanduran** [comment]
Osman beyin odasındaki bilgisayar Enes beyin masasına taşındı. Enes beyin bilgisayarı Betül hanıma taşındı. Enes bey Yasin beyin masasına geçti. Osman beyden alınan bilgisayar Yasin beye kuruldu. Betül hanımın maili kuruldu. Ve diğer maillerin kurulumu yapıldı.
