### ISSUE TITLE
Renki yazıcı için toner siparişi

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#45]
Mevcut olan yeni tonerler arasında sarı tonerimiz bulunmamaktadır. 
Bu tonerin isteğini Muhasebeden istek formu doldurarak yapalım.

**Comment by semihpro** [comment]
Talep formu doldurulup satınalmaya iletildi.

**Comment by 1serkanduran** [comment]
Satın alma Esran Hanımdan teslim alındı.
