### ISSUE TITLE
Gusto Raporların taşınması

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#50]
- [x] Gusto raporlarının ve diğer dosya dökümanların gerekli yerlere taşınması
- [x] Taşınan dosyaların yollarının kullanılan dosya ve programlarda güncellenmesi.

**Comment by 1OrhanCan** [comment]
Dosyalar 'GustoRaporlar' klasörünün içine taşındı

**Comment by 1OrhanCan** [comment]
Gusto uygulamasından rapor dosya yolu değiştirilip test edildi problemsiz çalışıyor
