### ISSUE TITLE
Yeni Pdf katalog

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#62]
Satış personeli Can bey tarafından örnek pdf ler verildi ve benzer olarak bizim katalogların uyarlanması istendi.

**Comment by semihpro** [comment]
İş Osman bey ile görüşüldü, Teknik ofis personeli Enes bey ile ben gerekli pdfleri hazırlayacağız.

**Comment by semihpro** [comment]
Yeni ve eski renkler olarak render işlemlerine Enes başladı.

**Comment by semihpro** [comment]
- Yapılan son müzakereye istinaden, renderlanacak resim sayısı azaltıldı. 
- Semirhan hanım takımları seçti ve pdf te yer alacak sahnelerin bulmasını sağladı. 
- Sahneler gece Betül ve Enes ile beraber bilgisayarlarına toplandı. 
- Sahnelerin olduğu disk tarafımıza yedeklenmek üzere kopyalandı.
- Can bey pdf düzenlemesinin dışında bırakıldı.

**Comment by 1serkanduran** [comment]
Katalog için incelenen siteler :
-Canva
-Flipsnack
-fliphtml5

**Comment by 1serkanduran** [comment]
-indesign çalışmalara başlandı. (20.12.2023)
-indesign ile birlikte tasarım çalışmalara yapıldı.
-Sayfa tasarımı dik olarak tasarlandı sunuldu.
-Yatay olmasına karar verildi.
-2 haftalık süreçte tasarım yapıldı ürünler eklendi.
-Tasarım bitti. Baskı için fiyat teklifleri Doğukan bey aracılığıyla görüşülme halinde.

**Comment by 1serkanduran** [comment]
-baskıcılardan teknik resimlerin düzgün çıkmayabileceği bilgisi geldi.
-Ezgi hanım ile birlikte teknik çizimler düzenleniyor.

**Comment by 1serkanduran** [comment]
-Teknik çizimler düzenlendi.
-Katalog çalışması bitti.
-Turmatsan firmasına gönderildi.
-Baskı için örnek bekleniyor.

**Comment by 1serkanduran** [comment]
-katalog tamamlandı firmalar ile baskı için göüşülüyor

**Comment by 1serkanduran** [comment]
-08.01.24 İstanbul'a gidildi.
-Fiyat teklifleri alındı.
-Uygun yer ile anlaşıldı.
@1OrhanCan

**Comment by 1OrhanCan** [comment]
Aydesa matbaacılık ile anlaşıldı 38.000+kdv olarak 1000 adet üzerinden anlaşıldı ödemenin yarısı işin başında kalanı iş tesliminde teslim edilcek fatma hanımdan ödeme için dönüş beklenmektedir

**Comment by 1serkanduran** [comment]
Pdf görselleri rgb olarak alınmış cmyk olarak çıkarılması istendi. Pdf çıktısı cmyk olarak alındı. Gönderildi.

**Comment by 1serkanduran** [comment]
dijital baskı kontrol edildi. katalog beğenilmedi. baskı yapılmayacağına karar verildi.
Fuarda qr olarak siteye yönlendirilecek.
