### ISSUE TITLE
IP telefon eksikliklerinin giderilmesi

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#7]
Ofis personellerine ulaşılması için IP telefonları aktif hale getirilecek ve eksik olan arkadaşlara IP telefon kurulumu yapılacaktır.

**Comment by 1serkanduran** [comment]
-Ip telefon eksiklikleri tespit edildi.
-Eksik noktalara telefonlar kuruldu.
-Telefon ayarları yapıldı ve numaralarda düzenlemeler yapıldı.
-Telefon rehberi oluşturuldu.
-Rehber kullanıcılara dağıtıldı.
@1OrhanCan
