### ISSUE TITLE
tabletlerin bakımı

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#71]
- [x] Tabletleri tamire gönderilecek
- [x] 2 adet adaptör edinilecek

**Comment by 1OrhanCan** [comment]
Tabletlerden biri Can beye teslim edildi Diğeri tamir edildi
2 adet başlık ve bir adet Type-c kablo alınması gerekiyordu Can bey istanbula gidince alacağını söyledi
