### ISSUE TITLE
İnstagram sayfası canlandırılması

### ISSUE THREAD

**Issue by 1serkanduran** [semihpro/RoderTeknikservis#72]
İnstagram sayfası kullanılmaya başlandı. Şu ana kadar 5 post ve 6 hikaye atıldı. 
Ürün görselleri boyutları düzeltilerek atılıyor.

**Comment by semihpro** [comment]
Instagram sayfasına yeni yayın, render fotoğrafları geldikten sonra yapılacak. Toplantı ortak kararı.

**Comment by semihpro** [comment]
Instagram sayfası başka bir arkadaşa bırakıldı.
