### ISSUE TITLE
Kamera kontrol (önemli)

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#73]
Su servisinden bir gün öncesinden başlayarak, tesisatları ve şartelleri kapatan arkadaşın tespiti yapılacak.
Muhasebe ye teknik servis gününü sorun.(Gün tespiti için)

**Comment by 1OrhanCan** [comment]
servis çarşamba günü gelmiş

**Comment by 1OrhanCan** [comment]
Mutfaktaki vana kapatılmış

**Comment by 1OrhanCan** [comment]
Mutfakta olduğu için mutfakta kamera olmadığı için takip edilemedi
