### ISSUE TITLE
Gusto hammadde maskeleme hatası

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#83]
Alt mamül açar iken mevcut kodlama standardı dışında 2 haneli olarak alt hesap açtırtıyor. 
Gerekli düzeltmeler gerekli alt ham maddeler için yapılmalı.

**Comment by 1OrhanCan** [comment]
Sol üstteki G amblemindenin Gusto sistem tanımlarına girip firmaya bağlı tanımlara tıklayıp sol üstten tekrar G logosuna tıklayıp dönem seçip daha sonra kod kısmından stok seçip ayarlama yapıldı

**Comment by 1OrhanCan** [comment]
![Screenshot_1](https://github.com/semihpro/RoderTeknikservis/assets/149588286/72b475f2-30e6-427b-8624-8fc15a7a7b4c)
