### ISSUE TITLE
Banka exceli kontrol edilecek

### ISSUE THREAD

**Issue by semihpro** [semihpro/RoderTeknikservis#9]
Funda Aytekin diyarbakır merkes Finans dosya açarken sıkıntı yaşıyor.

**Comment by semihpro** [comment]
Cuma günü güncel bir excel ile deneme yapılacak

**Comment by semihpro** [comment]
Bir excel 2019 da kaydetilip Funda hanıma Fatma hanım üzerinden gönderildi.

**Comment by semihpro** [comment]
Mevcut excel sürümü 2019 ve üzeri olması gerekiyor. Bugün saat 4 ten sonra yeni versiyon office kurulumu yapılacak.

**Comment by 1OrhanCan** [comment]
Kurulum yapıldı
